name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Step to checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Generates the snake animation SVG from the GitHub user contributions
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: NayakPratheek
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Push the generated SVG files to the specified branch
      - name: Push GitHub Contribution Grid Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
